# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and function

# Set Hadoop-related environment variables
 
export HADOOP_HOME=$HOME/hadoop
 
export HADOOP_CONF_DIR=$HOME/hadoop/etc/hadoop
 
export HADOOP_MAPRED_HOME=$HOME/hadoop
 
export HADOOP_COMMON_HOME=$HOME/hadoop
 
export HADOOP_HDFS_HOME=$HOME/hadoop
 
export YARN_HOME=$HOME/hadoop
  
# Set JAVA_HOME
 
export JAVA_HOME=/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.95.x86_64/jre
 
export PATH=$PATH:$JAVA_HOME/bin
 
# Add Hadoop bin/ directory to PATH
 
export PATH=$PATH:$HOME/hadoop/bin

export HADOOP_CLASSPATH=/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.95.x86_64/lib/tools.jar
